from __future__ import annotations

from . import genr

class Page(genr._PageProps, genr._PageLists):
    """
    Attributes:
        title: The full Namespace:Title of the page.
    """

    title: str
    wiki: Wiki

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.page`."""
        raise NotImplementedError

    async def read(self) -> str:
        """Read the contents of the ``main`` revision slot."""
        raise NotImplementedError

    async def edit(
        self, content: str, summary: str, *,
        section: int | None = None,
        minor: bool | None = None,
        bot: bool = True,
        ignore_conflicts: bool = False,
        create: bool | None = False,
    ) -> None:
        """Edit the page.

        Parameters:
            content: The new content to appear on the page.
            summary: Edit summary. If empty, one may be automatically generated
                by MediaWiki.
            section: ``content`` is for the ``section``-th section (where 0 is
                the top, title-less section).
            minor: If :data:`True` (or :data:`None` and the "Mark all edits
                minor by default" preference is set), mark this edit as minor.
            bot: Mark this edit as a bot edit.
            ignore_conflicts: Do not check for edit conflicts; just make the
                edit. (Not recommended.)
            create: If :data:`True`, *don't* edit an existing page. If
                :data:`False`, *only* edit an existing page. If :data:`None`,
                the edit is agnostic of whether the page exists.

        Raises:
            APIError: If editing failed.
        """
        raise NotImplementedError

    async def delete(
        self, reason: str, *,
        delete_talk: bool = False,
    ) -> None:
        """Delete the page.

        Parameters:
            reason: Reason for the deletion. If empty, one may be automatically
                generated by MediaWiki.
            delete_talk: If :data:`True`, delete the associated talk page, if
                it exists.

        Raises:
            APIError: If deleting failed.
        """
        raise NotImplementedError

    def talk(self) -> TalkPage:
        """Get the talk page associated with this page."""
        raise NotImplementedError

    def as_talk(self) -> TalkPage:
        """Get the same page as if it was a talk page.
        Useful for pages with ``__NEWSECTIONLINK__``.
        """
        raise NotImplementedError

    def as_template(self) -> Template:
        """Get the same page as if it was a template.
        Useful for non-template transcluded pages.
        """
        raise NotImplementedError

    def __or__(self, other: Page) -> Pages:
        """Combine this page with another for a multi-page fetch."""
        raise NotImplementedError

class TalkPage(Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Page.talk()` or
        :meth:`Page.as_talk()`.
        """
        raise NotImplementedError

    async def new_section(
        self, title: str, content: str, *,
        minor: bool | None = None,
        bot: bool = True,
    ) -> None:
        """Create a new section on the talk page.

        Parameters:
            title: Title of the new section
            content: Text of the new section. Remember to include a signature.
            minor: See :meth:`Page.edit()`
            bot: See :meth:`Page.edit()`

        Raises:
            APIError: If editing failed.
        """
        raise NotImplementedError

class File(genr._FileProps, genr._FileLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.file`."""
        raise NotImplementedError

class Template(genr._TemplateProps, genr._TemplateLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.template` or :meth:`Page.as_template`."""
        raise NotImplementedError

class Category(genr._CategoryProps, genr._CategoryLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.category`."""
        raise NotImplementedError

class Pages(genr._PageProps):
    """The result of combining more than one :class:`Page`."""

class Categories(genr._CategoryProps):
    """The result of combining more than one :class:`Category`."""

class Files(genr._FileProps):
    """The result of combining more than one :class:`File`."""

class Templates(genr._TemplateProps):
    """The result of combining more than one :class:`Template`."""

from .wiki import Wiki
from . import user
