from __future__ import annotations
from datetime import datetime
import io
from typing import TYPE_CHECKING, AsyncGenerator, Generic, Literal, Self, TypeVar, overload

from . import genr
if TYPE_CHECKING:
    from .misc import Namespace, Tag

class Page(genr._PageProps, genr._PageLists):
    """
    A handle on a wiki page, uniquely identified by its :attr:`title`. There is
    only one :class:`Page` instance per :class:`Wiki` per
    MediaWiki-normalized title.

    The :attr:`title` |key-attr| |population| :meth:`update_info`.

    Attributes:
        title: The full Namespace:Title of the page.
    """

    title: str
    wiki: Wiki

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.page`."""
        raise NotImplementedError

    async def edit(
        self, content: str, summary: str, *,
        section: int | None = None,
        minor: bool | None = None,
        bot: bool = True,
        ignore_conflicts: bool = False,
        create: bool | None = False,
        tags: list[Tag] | None = None,
    ) -> None:
        """Edit the page.

        Parameters:
            content: The new content to appear on the page.
            summary: Edit summary. If empty, one may be automatically generated
                by MediaWiki.
            section: ``content`` is for the ``section``-th section (where 0 is
                the top, title-less section).
            minor: If :data:`True` (or :data:`None` and the "Mark all edits
                minor by default" preference is set), mark this edit as minor.
            bot: Mark this edit as a bot edit.
            ignore_conflicts: Do not check for edit conflicts; just make the
                edit. (Not recommended.)
            create: If :data:`True`, *don't* edit an existing page. If
                :data:`False`, *only* edit an existing page. If :data:`None`,
                the edit is agnostic of whether the page exists.
            tags: Manually apply these recent change tags to the edit.

        Raises:
            APIError: If editing failed.
        """
        raise NotImplementedError

    async def delete(
        self, reason: str, *,
        delete_talk: bool = False,
    ) -> None:
        """Delete the page.

        Parameters:
            reason: Reason for the deletion. If empty, one may be automatically
                generated by MediaWiki.
            delete_talk: If :data:`True`, delete the associated talk page, if
                it exists.

        Raises:
            APIError: If deleting failed.
        """
        raise NotImplementedError

    @property
    def talk(self) -> TalkPage:
        """The talk page associated with this page."""
        raise NotImplementedError

    @property
    def namespace(self) -> Namespace:
        """The namespace to which this page belongs."""
        raise NotImplementedError

    @property
    def missing(self) -> bool:
        """If :const:`True`, the page does not exist
        and most methods/properties will fail.
        """
        raise NotImplementedError

    def as_talk(self) -> TalkPage:
        """Get the same page as if it was a talk page.
        Useful for pages with ``__NEWSECTIONLINK__``.
        """
        raise NotImplementedError

    def as_template(self) -> Template:
        """Get the same page as if it was a template.
        Useful for non-template transcluded pages.
        """
        raise NotImplementedError

    @overload
    def __or__(self: Category, other: Category) -> Categories: ...
    @overload
    def __or__(self: File, other: File) -> Files: ...
    @overload
    def __or__(self: Template, other: Template) -> Templates: ...
    @overload
    def __or__(self: Page, other: Page) -> Pages: ...
    def __or__(self, other: T) -> Pages | _Pages[T]:
        """Combine this page with another for a multi-page fetch."""
        raise NotImplementedError

    def __truediv__(self, other: str) -> Self:
        """Get a subpage of this page (if enabled in this namespace.)"""
        raise NotImplementedError

class TalkPage(Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Page.talk()` or
        :meth:`Page.as_talk()`.
        """
        raise NotImplementedError

    async def new_section(
        self, title: str, content: str, *,
        minor: bool | None = None,
        bot: bool = True,
        summary: str | None = None
    ) -> None:
        """Create a new section on the talk page.

        Parameters:
            title: Title of the new section
            content: Text of the new section. Remember to include a signature.
            minor: See :meth:`Page.edit()`
            bot: See :meth:`Page.edit()`
            summary: Edit summary (generated from ``title`` if omitted)

        Raises:
            APIError: If editing failed.
        """
        raise NotImplementedError

class File(genr._FileProps, genr._FileLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.file`."""
        raise NotImplementedError

    async def upload(
        self, file: io.IOBase | str, summary: str, *,
        tags: list[Tag] | None = None,
        text: str | None = None,
        ignore_warnings: bool = False,
    ) -> None:
        """Upload a new file or file version.

        Parameters:
            file: Either a file object with the contents to upload, or an URL
                to the file to upload.
            summary: Upload comment; also initial File: page content if
                ``text`` is :const:`None`.
            tags: Manually apply these recent change tags to the upload.
            text: Initial File: page content for a new upload.
            ignore_warnings: If :const:`True`, ignore any upload warnings.
        """
        raise NotImplementedError

    @property
    def repository(self) -> Literal['local'] | str:
        """Repository on which this image is stored (if applicable)."""
        raise NotImplementedError

class Template(genr._TemplateProps, genr._TemplateLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.template` or :meth:`Page.as_template`."""
        raise NotImplementedError

    def transclude(self, *args: str, **kwargs: str) -> str:
        title = self.title.removeprefix(
            self.wiki.namespace('Template').name + ':')
        positional = ''.join('|' + arg for arg in args)
        keyword = ''.join(f'|{key}={value}' for key, value in kwargs)
        return '{{%s%s%s}}' % (title, positional, keyword)

class Category(genr._CategoryProps, genr._CategoryLists, Page):

    def __init__(self) -> None:
        """|noinit| Use :meth:`Wiki.category`."""
        raise NotImplementedError

T = TypeVar('T', bound=Page)

class _Pages(Generic[T]):
    def __aiter__(self) -> AsyncGenerator[T, None]:
        """Generate just the pages in this set."""
        raise NotImplementedError

    def __or__(self, other: T | Self) -> Self:
        """Add more pages to this set."""
        raise NotImplementedError

class Pages(_Pages[Page], genr._PageProps):
    """The result of combining more than one :class:`Page`."""

class Categories(_Pages[Category], genr._CategoryProps):
    """The result of combining more than one :class:`Category`."""

class Files(_Pages[File], genr._FileProps):
    """The result of combining more than one :class:`File`."""

class Templates(_Pages[Template], genr._TemplateProps):
    """The result of combining more than one :class:`Template`."""

class Revision:
    """
    A handle on a wiki page revision, uniquely identified by its :attr:`id`.
    There is only one :class:`Revision` instance per :class:`Wiki` per ID.

    The :attr:`id` |key-attr| |population| :meth:`update_info`.

    Attributes:
        id: The revision ID.
    """

    id: int
    wiki: Wiki

    def __init__(self) -> None:
        """|noinit|"""
        raise NotImplementedError

    async def update_info(self) -> None:
        """Fetch all available metadata about the revision and cache it,
        updating the cache if previously fetched.

        After calling this method, every :class:`property` of this instance
        should return data instead of raising :exc:`KeyError`.

        Raises:
            APIError: If fetching data failed (e.g. because the revision does
                not exist)
        """
        raise NotImplementedError

    async def patrol(self) -> bool:
        """Patrol the recent change corresponding to this revision.

        This is an expensive call. It requires first looking up the recent
        change corresponding to this revision, then patrolling it if it is
        unpatrolled. The corresponding MediaWiki diff functionality really
        does do this too, but it has the advantage of direct database access.

        Returns:
            :const:`True` if the revision was patrolled, or :const:`False`
            if it was already patrolled.

        Raises:
            APIError: If fetching data failed (e.g. because the revision does
                not exist) or patrolling failed.
        """
        raise NotImplementedError

    @property
    def page(self) -> Page:
        """The page this revision was made to."""
        raise NotImplementedError

    @property
    def parent(self) -> Revision | None:
        """The revision preceding this one, if there is one."""
        raise NotImplementedError

    @property
    def minor(self) -> bool:
        """Whether this revision was a minor edit."""
        raise NotImplementedError

    @property
    def user(self) -> user.User:
        """The user that made this revision."""
        raise NotImplementedError

    @property
    def timestamp(self) -> datetime:
        """The timestamp when this revision was made."""
        raise NotImplementedError

    @property
    def size(self) -> int:
        """The size of the page content at this revision."""
        raise NotImplementedError

    @property
    def comment(self) -> str:
        """The edit summary for this revision."""
        raise NotImplementedError

    @property
    def tags(self) -> list[Tag]:
        """The recent change tags associated with this edit."""
        raise NotImplementedError

from .wiki import Wiki
from . import user
