---
displayMode: compact
---
gantt
    dateFormat YYYY-MM-DD
    axisFormat '%y

    section 1.43
    MediaWiki 1.43: 2024-12-21, 2027-12-31
    mw-api-client 4.43.*.*: crit, 2026-05-31, 2027-12-31

    section Python
    Python 3.13 (bugfix): p13, 2024-10-07, 2y
    Python 3.13 (security): after p13, 3y
    Python 3.14 (bugfix): p14, 2025-10-07, 2y
    Python 3.14 (security): after p14, 3y

    section 1.47
    MediaWiki 1.47 (projected): 2026-12-01, 2029-12-31
    mw-api-client 4.47.*.*: crit, 2026-12-01, 2029-12-31
