from getpass import getpass
from importlib.metadata import version as get_version
import asyncio
import mw_api as mw
import mwparserfromhell as mwp

async def login_wiki() -> mw.Wiki:
    """Initialize and log into the wiki.
    Return the authenticated Wiki instance.
    """
    # Get a handle on the wiki we are acting on.
    # The second parameter is the user agent, and is required
    wiki = await mw.Wiki.new(
        # Example: https://en.wikipedia.org/w/api.php
        # All requests made are to this URL (+ query parameters).
        input('Enter URL to api.php: '),
        # This is the user agent, and is required (rather than providing a default)
        f'mw-api-client-demo/0.0.0, mw-api-client/{get_version("mw-api-client")}'
    )

    # Login with a bot password. For this to work, you need to have
    # generated a password on Special:BotPasswords.
    await wiki.login(input('Enter username: '), getpass('Enter password: '))

    return wiki

async def sandbox_play(wiki: mw.Wiki) -> mw.Page:
    """Play around with the logged-in user's sandbox."""
    assert wiki.me is not None
    # Get a handle on a wiki page
    sandbox = wiki.page(f'User:{wiki.me.name}/sandbox')

    # Create or replace the contents of the page
    content = 'Initial contents'
    await sandbox.edit(
        content=content,
        # Required parameter. In the rare case where providing an edit summary
        # is forbidden, pass None explicitly. Note that in that case, MediaWiki
        # may automatically generate an edit summary for you.
        summary='Initializing the sandbox',
        # By default, edits can't create new pages (create=False);
        # create=None makes it agnostic; create=True allows only creation.
        create=None,
    )

    # Ensure our changes were made, minus the extra trailing newline.
    # This also internally marks the respective revision as the the "base"
    # revision used for edit conflict detection.
    assert content == (content := await sandbox.read()).rstrip()

    # Modify the content
    content += '\nNew test'
    await sandbox.edit(content, 'Making a test edit')

    return sandbox

async def post_message(page: mw.Page) -> None:
    """Post a message on the talk page associated with the given page."""
    # Get the talk page associated with the given page
    talk: mw.TalkPage = page.talk

    # Add a new section at the bottom of the page.
    await talk.new_section(
        # Section title
        'I made an edit!',
        # Section text - signature must be explicitly included
        'I thought I would make a few edits for demo purposes.~~~~'
    )

async def generators_demo(wiki: mw.Wiki) -> None:
    """Print pages generated by a few example generators."""
    page1 = wiki.page('Page 1')
    page2 = wiki.page('Page 2')

    #   Iterate over the categories to which the pages to which `page1` links
    # belong. That is - for each page `page1` links to, include the
    # categories that page belongs to in the resulting iterator.
    # Each `linked_page`, therefore, appears once per `category` result.
    #   The `async for` is necessary because results are yielded as they are
    # returned by the API; when a limit-continue point is reached, that
    # iteration of the Python loop will perform the necessary request.
    #   `limit=None` means keep looping until we go through all available
    # results for `links()`. You can instead pass an integer to fetch that many
    # results, or pass the literal string 'max' for the maximum number the API
    # will allow you to fetch in one request. No limit can be passed to
    # categories() due to the nature of the API's limit-continue system; all
    # available results will always be fetched. The exception is if the limit
    # for the generator is 1.
    async for linked_page, category in page1.links(limit=None).categories():
        print(page1, 'links to', linked_page, 'which is in category', category.title)

    #   Fetch both contributors to, and templates used in, the first 5 pages
    # that link to `page1` OR `page2`. That is - for each page that links to
    # either `page1` or `page2`, include both the (logged-in) users that
    # contributed to that page and the templates that page uses in the
    # resulting data.
    #   Unlike the previous example, results have to be returned all at once
    # because there is no good way to structure that kind of iteration in a way
    # that doesn't involve prefetching all the data anyway.
    generator = (page1 | page2).links_here(limit=5)
    results = await (generator.contributors() | generator.templates()).fetchall()
    for linking_page, result in results.items():
        for user in result['contributors']:
            print(page1, 'or', page2, 'links to', linking_page, 'which has contributor', user)
        for template in result['templates']:
            print(page1, 'or', page2, 'links to', linking_page, 'which uses template', template)

async def remove_category(cat: mw.Category) -> None:
    """Delete a category and remove all links to it."""
    # Remove the category link from every page.
    # We use Earwig's mwparserfromhell to make the changes.
    async for page in cat.pages():
        # Get and parse the page content
        content = mwp.parse(await page.read())
        # Loop through all links and remove links to the category
        for link in content.filter_wikilinks():
            if link.title == cat.title:
                content.remove(link)
        # Save the content
        summary = f'Automatically removing link to {cat.title} before its deletion'
        print(summary, 'from', page)
        await page.edit(str(content), summary)
        # Pause 1 second between edits
        await asyncio.sleep(1)
    # Now we can delete the category
    print('Deleting', cat)
    await cat.delete('Automatically deleting unused category')

async def patrol_all_help(wiki: mw.Wiki) -> None:
    """Patrol all changes in the Help namespace."""
    # Only fetch unpatrolled changes in the Help namespace
    async for change in wiki.recentchanges(
        limit=None, namespace=wiki.namespace('Help'),
        show=['unpatrolled']
    ):
        # Patrol the change
        print('Patrolling change to', change.title)
        await change.patrol()
        # Pause 1 second between patrols
        await asyncio.sleep(1)

async def main() -> None:
    wiki = await login_wiki()

    sandbox = await sandbox_play(wiki)
    await post_message(sandbox)

    await generators_demo(wiki)

    # wiki.category() returns a mw.Category which is a subclass of mw.Page with
    # extra features specific to categories
    await remove_category(wiki.category('Category:Unused category'))

    await patrol_all_help(wiki)

asyncio.run(main())
